name: Build and Test w/Bazel
permissions: read-all
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2

      - name: Cache bazel build artifacts
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # pin@v4.2.3
        with:
          path: |
            ~/.cache/bazel
          # add import_llvm.bzl so that a new build occurs after an LLVM commit hash update
          key: ${{ runner.os }}-bazel-${{ hashFiles('bazel/import_llvm.bzl') }}-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE') }}
          restore-keys: |
            ${{ runner.os }}-bazel-${{ hashFiles('bazel/import_llvm.bzl') }}

      - name: "Run `bazel build`"
        run: |
          bazel build -c fastbuild //...

      - name: "Run `bazel test`"
        run: |
          bazel test -c fastbuild //...
